import { expect, test } from '@playwright/test'

const errors: string[] = []
test.beforeEach(async ({ page }) => {
  errors.length = 0
  page.on('pageerror', (error) => errors.push(error.message))
})
test.afterEach(() => expect(errors).toEqual([]))

test('server-rendered gallery exposes only the six reference palettes and copies a swatch', async ({ page, context, request }) => {
  const response = await request.get('/')
  expect(response.status()).toBe(200)
  expect(await response.text()).toContain('蒙德里安色系')
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('色系')
  await expect(page.locator('.palette-card')).toHaveCount(6)
  await expect(page.locator('.card-info h2')).toHaveText(['蒙德里安色系', '孟菲斯色系', '洛可可色系', '马卡龙色系', '敦煌色系', '莫兰迪色系'])
  await page.getByRole('button', { name: '复制 #1286DD', exact: true }).click()
  await expect(page.getByText('已复制到剪贴板')).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('#1286DD')
  await page.screenshot({ path: 'test-results/gallery-desktop.png', fullPage: true })
})

test('live artwork recoloring, comparison, reset and whole palette copying work', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/palettes/mondrian')
  await expect(page).toHaveTitle(/蒙德里安色系/)
  await expect(page.getByText('色系参考')).toHaveCount(0)
  const canvas = page.locator('canvas')
  const pixels = () => canvas.evaluate((element: HTMLCanvasElement) => Array.from(element.getContext('2d')!.getImageData(600, 250, 1, 1).data))
  await expect.poll(async () => (await pixels())[3]).toBe(255)
  const original = await pixels()
  await page.getByLabel('选择颜色 1', { exact: true }).fill('#2468ac')
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#2468AC')
  await expect.poll(pixels).not.toEqual(original)
  const edited = await pixels()
  await page.getByRole('button', { name: '查看原色' }).click()
  await expect.poll(pixels).toEqual(original)
  await page.getByRole('button', { name: '返回调色' }).click()
  await expect.poll(pixels).toEqual(edited)
  await page.getByRole('button', { name: '恢复原色' }).click()
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#F50F0F')
  await expect.poll(pixels).toEqual(original)
  await page.getByRole('button', { name: '复制整组色值' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('#F50F0F, #1286DD, #FFF100, #FFFFFF, #F66814')
  await page.screenshot({ path: 'test-results/palette-desktop.png', fullPage: true })
  await page.getByRole('link', { name: '孟菲斯色系' }).click()
  await expect(page).toHaveURL(/\/palettes\/memphis$/)
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#F964C2')
})

test('personal palettes persist, reopen, update, delete and undo without modifying presets', async ({ page }) => {
  await page.goto('/palettes/morandi')
  await page.getByLabel('颜色 1 HEX').fill('#CC7788')
  await page.getByRole('button', { name: '保存为个人色系' }).click()
  await page.getByLabel('色系名称').fill('   ')
  await page.getByRole('button', { name: '确认保存' }).click()
  await expect(page.getByText('请为色系取个名字。')).toBeVisible()
  await page.getByLabel('色系名称').fill('雨后的花园')
  await page.getByRole('button', { name: '确认保存' }).click()
  await expect(page).toHaveURL(/saved=/)
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('雨后的花园')
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#CC7788')
  await page.getByLabel('颜色 2 HEX').fill('#CC7788')
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.getByRole('button', { name: '确认保存' }).click()
  await page.getByRole('link', { name: '返回色系库' }).click()
  await expect(page.locator('#personal .palette-card')).toHaveCount(1)
  await page.getByRole('link', { name: '预览雨后的花园' }).click()
  await expect(page.getByLabel('颜色 2 HEX')).toHaveValue('#CC7788')
  await page.getByRole('link', { name: '返回色系库' }).click()
  await page.getByRole('button', { name: '删除雨后的花园' }).click()
  await expect(page.locator('#personal .palette-card')).toHaveCount(0)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.locator('#personal .palette-card')).toHaveCount(1)
  await page.getByRole('link', { name: '预览莫兰迪色系' }).click()
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#3A4E59')
})

test('save failure preserves edits and does not report success', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError') } })
  await page.goto('/palettes/macaron')
  await page.getByLabel('颜色 1 HEX').fill('#112233')
  await page.getByRole('button', { name: '保存为个人色系' }).click()
  await page.getByRole('button', { name: '确认保存' }).click()
  await expect(page.getByText('保存失败，请检查浏览器是否允许本地存储。当前调色仍保留在页面中。')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('颜色 1 HEX')).toHaveValue('#112233')
  await expect(page).not.toHaveURL(/saved=/)
})

test('feedback validates whitespace, prepares encoded issue and restores trigger focus', async ({ page }) => {
  await page.addInitScript(() => {
    window.open = (url) => { document.documentElement.dataset.openedUrl = String(url); return null }
  })
  await page.goto('/palettes/dunhuang')
  const trigger = page.getByRole('button', { name: '意见反馈' })
  await trigger.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  await expect(page.getByText('请填写反馈标题。')).toBeVisible()
  await expect(page.getByText('请补充反馈内容。')).toBeVisible()
  await page.getByLabel('标题', { exact: false }).fill('   ')
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  await expect(page.getByText('请填写反馈标题。')).toBeVisible()
  await page.getByLabel('标题', { exact: false }).fill('蓝色 & 紫色 # 对比')
  await page.getByLabel('详细描述', { exact: false }).fill('希望添加深色主题。\n保留中文与特殊字符 & # +。')
  await page.getByLabel('反馈类型').selectOption('功能建议')
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  const url = new URL(await page.locator('html').getAttribute('data-opened-url') as string)
  expect(url.origin + url.pathname).toBe('https://github.com/fine405/hue-atlas/issues/new')
  expect(url.searchParams.get('title')).toBe('[功能建议] 蓝色 & 紫色 # 对比')
  expect(url.searchParams.get('body')).toContain('敦煌色系 (dunhuang)')
  expect(url.searchParams.get('body')).toContain('保留中文与特殊字符 & # +。')
  await expect(page.getByRole('link', { name: '点击继续 →' })).toHaveAttribute('href', url.toString())
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('mobile gallery, detail and feedback fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.palette-card')).toHaveCount(6)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/gallery-mobile.png', fullPage: true })
  await page.getByRole('link', { name: '预览蒙德里安色系' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('蒙德里安色系')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '意见反馈' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: 'test-results/feedback-mobile.png' })
  await expect(page.getByRole('button', { name: '在 GitHub 中继续' })).toBeInViewport()
})

test('removed palettes return a real 404 with recovery navigation', async ({ page }) => {
  const response = await page.goto('/palettes/matcha-latte')
  expect(response?.status()).toBe(404)
  await expect(page.getByRole('heading', { name: '这抹颜色还没有被收录' })).toBeVisible()
  await page.getByRole('link', { name: '返回色系库 →' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('色系')
})

test('all six reference artworks load and missing personal links recover', async ({ page }) => {
  for (const id of ['mondrian', 'memphis', 'rococo', 'macaron', 'dunhuang', 'morandi']) {
    await page.goto(`/palettes/${id}`)
    await expect(page.locator('.artwork')).toHaveAttribute('data-render-state', 'ready')
    await expect(page.locator('canvas')).toBeVisible()
    await expect.poll(() => page.locator('canvas').evaluate((canvas: HTMLCanvasElement) => canvas.getContext('2d')!.getImageData(100, 100, 1, 1).data[3])).toBe(255)
    await page.locator('.artwork').screenshot({ path: `test-results/artwork-${id}.png` })
    await page.getByLabel('颜色 1 HEX').fill('#FF00FF')
    await expect(page.getByRole('button', { name: '查看原色' })).toBeEnabled()
  }
  await page.goto('/palettes/mondrian?saved=missing')
  await expect(page.getByRole('heading', { name: '此浏览器中没有这组色系' })).toBeVisible()
  await page.getByRole('link', { name: '返回我的色系 →' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('色系')
})
