import { expect, test } from '@playwright/test'

const errors: string[] = []
test.beforeEach(async ({ page }) => {
  errors.length = 0
  page.on('pageerror', (error) => errors.push(error.message))
})
test.afterEach(() => expect(errors).toEqual([]))

test('server-rendered gallery exposes all 12 palettes and copies a swatch', async ({ page, context, request }) => {
  const response = await request.get('/')
  expect(response.status()).toBe(200)
  expect(await response.text()).toContain('抹茶拿铁')
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('好设计')
  await expect(page.locator('.palette-card')).toHaveCount(12)
  await page.getByRole('button', { name: '复制 #52684A', exact: true }).click()
  await expect(page.getByText('已复制到剪贴板')).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('#52684A')
  await page.screenshot({ path: 'test-results/gallery-desktop.png', fullPage: true })
})

test('palette deep link, whole palette copy and real component interactions work', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/palettes/matcha-latte')
  await expect(page).toHaveTitle(/抹茶拿铁/)
  await page.getByRole('button', { name: '复制整组色值' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('#28382D, #52684A, #A3B18A, #DADFCB, #F5F3E8')
  const task = page.getByRole('button', { name: '为新项目收集一些灵感' })
  await task.click()
  await expect(page.getByRole('button', { name: '完成啦，做得不错！' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: '添加灵感' })).toBeDisabled()
  await page.getByLabel('记下此刻的想法').fill('今天的配色')
  await page.getByRole('button', { name: '添加灵感' }).click()
  await expect(page.getByText('预览交互成功')).toBeVisible()
  await page.screenshot({ path: 'test-results/palette-desktop.png', fullPage: true })
  await page.getByRole('link', { name: '赤陶日落' }).click()
  await expect(page).toHaveURL(/\/palettes\/terracotta$/)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('赤陶日落')
})

test('feedback validates whitespace, prepares encoded issue and restores trigger focus', async ({ page }) => {
  await page.addInitScript(() => {
    window.open = (url) => { document.documentElement.dataset.openedUrl = String(url); return null }
  })
  await page.goto('/palettes/cobalt-studio')
  const trigger = page.getByRole('button', { name: '反馈这组配色' })
  await trigger.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  await expect(page.getByText('请填写反馈标题。')).toBeVisible()
  await expect(page.getByText('请补充反馈内容。')).toBeVisible()
  await page.getByLabel('标题', { exact: false }).fill('   ')
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  await expect(page.getByText('请填写反馈标题。')).toBeVisible()
  await page.getByLabel('标题', { exact: false }).fill('蓝色 & 紫色 # 对比')
  await page.getByLabel('详细描述', { exact: false }).fill('希望添加深色主题。\n保留中文与特殊字符 & # +。')
  await page.getByLabel('反馈类型').selectOption('功能建议')
  await page.getByRole('button', { name: '在 GitHub 中继续' }).click()
  const url = new URL(await page.locator('html').getAttribute('data-opened-url') as string)
  expect(url.origin + url.pathname).toBe('https://github.com/fine405/hue-atlas/issues/new')
  expect(url.searchParams.get('title')).toBe('[功能建议] 蓝色 & 紫色 # 对比')
  expect(url.searchParams.get('body')).toContain('钴蓝工作室 (cobalt-studio)')
  expect(url.searchParams.get('body')).toContain('保留中文与特殊字符 & # +。')
  await expect(page.getByRole('link', { name: '点击继续 →' })).toHaveAttribute('href', url.toString())
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('mobile gallery, detail and feedback fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.palette-card')).toHaveCount(12)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/gallery-mobile.png', fullPage: true })
  await page.getByRole('link', { name: '预览抹茶拿铁' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('抹茶拿铁')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '意见反馈' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: 'test-results/feedback-mobile.png' })
  await expect(page.getByRole('button', { name: '在 GitHub 中继续' })).toBeInViewport()
})

test('unknown palettes return a real 404 with recovery navigation', async ({ page }) => {
  const response = await page.goto('/palettes/not-a-palette')
  expect(response?.status()).toBe(404)
  await expect(page.getByRole('heading', { name: '这抹颜色还没有被收录' })).toBeVisible()
  await page.getByRole('link', { name: '返回色系库 →' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('好设计')
})
