/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PalettesPaletteIdRouteImport } from './routes/palettes.$paletteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettesPaletteIdRoute = PalettesPaletteIdRouteImport.update({
  id: '/palettes/$paletteId',
  path: '/palettes/$paletteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/palettes/$paletteId': typeof PalettesPaletteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/palettes/$paletteId': typeof PalettesPaletteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/palettes/$paletteId': typeof PalettesPaletteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/palettes/$paletteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/palettes/$paletteId'
  id: '__root__' | '/' | '/palettes/$paletteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalettesPaletteIdRoute: typeof PalettesPaletteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palettes/$paletteId': {
      id: '/palettes/$paletteId'
      path: '/palettes/$paletteId'
      fullPath: '/palettes/$paletteId'
      preLoaderRoute: typeof PalettesPaletteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalettesPaletteIdRoute: PalettesPaletteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
